name: "💡 Feature Request"
description: Create a new ticket for a new feature request
title: "💡 [SUGESTÃO] - <title>"

labels: ["question"]
body:
  - type: textarea
    id: resumo
    attributes:
      label: "Resumo"
      description: Forneça uma breve explicação sobre a sugestão
      placeholder: Sua sugestão está relacionada a um problema? Por favor descreva
    validations:
      required: true
  - type: textarea
    id: descricao
    attributes:
      label: "Descrição"
      description: Descreva a solução que você deseja
      placeholder: Uma descrição clara e concisa do que você deseja que aconteça.
    validations:
      required: true
  - type: textarea
    id: alternativas
    attributes:
      label: "Alternativas"
      description: Descreva as alternativas que você considerou
      placeholder: Uma descrição clara e concisa de quaisquer soluções ou recursos alternativos que você considerou.
    validations:
      required: true
  - type: textarea
    id: adicional
    attributes:
      label: "Adicional"
      description: Contexto adicional
      placeholder: Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.
    validations:
      required: false
  - type: dropdown
    id: trabalhar
    attributes:
      label: "Trabalhar"
      description: Você tem interesse em trabalhar nisso?
      multiple: true
      options:
        - Sim
        - Não
